# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ภาษาไอริน
email: dev@irin.in.th
description: "การเยื้องเพื่อการรู้จำภาษาธรรมชาติอย่างชาญฉลาด (Indent to Recognize for Intelligent Natural language : IRIN) หรือเรียกอีกชื่อว่า ภาษาไอริน โดยใช้การเยื้องของโค้ดให้เป็นประโยชน์ในบอกรูปแบบของประโยคคำถามและคำตอบในการสร้างระบบสนทนาโต้ตอบอัตโนมัติซึ่งจะทำให้โค้ดอ่านง่ายและสั้นลงอย่างมากซึ่งเป็นมิตรต่อผู้ที่กำลังศึกษาการสร้างระบบสนทนาโต้ตอบอัตโนมัติและยังทำให้สามารถพัฒนาระบบได้อย่างรวดเร็วอีกทั้งยังรองรับการใช้งานทั้งภาษาไทยและภาษาอังกฤษ"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ภาษา.ไอริน.ไทย" # the base hostname & protocol for your site
lang_eng_baseurl: "/"
lang_eng_url: "https://lang.irin.in.th"
permalink: /:year/:month/:title.html
social:
  gplus: 113820425408268226106
  fb: 100000131794195
  fbapps: 351070565012663
  twitter: "@PakkaponPH"
encoding: utf-8
binary:
  version: 0.0.2
  link: https://github.com/pureexe/irin-lang/releases
# Build settings
markdown: kramdown
gems:
  - jekyll-redirect-from
